package dk.naturerhverv.fishery.sm.cmon.common.findconversionfactor.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-10-27T13:08:18.933+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindConversionFactor:v1.0", name = "CMON.Conversion.FindConversionFactor")
@XmlSeeAlso({dk.naturerhverv.fishery.dm.base.v1.ObjectFactory.class, dk.naturerhverv.fishery.sm.cmon.common.findconversionfactor.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CMONConversionFindConversionFactor {

    @WebMethod(operationName = "FindConversionFactorType", action = "FindConversionFactorType")
    @WebResult(name = "FindConversionFactorRes", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindConversionFactor:v1.0", partName = "part")
    public dk.naturerhverv.fishery.sm.cmon.common.findconversionfactor.v1.FindConversionFactorRes findConversionFactorType(
        @WebParam(partName = "part", name = "FindConversionFactorReq", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindConversionFactor:v1.0")
        dk.naturerhverv.fishery.sm.cmon.common.findconversionfactor.v1.FindConversionFactorReq part
    );
}
