package dk.naturerhverv.fishery.service.lists.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-10-27T14:24:33.226+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:dk:naturerhverv:fishery:service:lists:v1", name = "LIST.Common.GetLists")
@XmlSeeAlso({dk.fd.dm.geod.v1.ObjectFactory.class, dk.naturerhverv.fishery.lists.v1.ObjectFactory.class, dk.naturerhverv.fishery.base.common.v1.ObjectFactory.class, ObjectFactory.class, dk.naturerhverv.fishery.lists.v2.ObjectFactory.class, dk.naturerhverv.fishery.dm.base.v1.ObjectFactory.class, dk.fd.dm.indv.v1.ObjectFactory.class, dk.naturerhverv.fishery.dm.geod.v1.ObjectFactory.class, dk.fd.dm.ctrl.v1.ObjectFactory.class, dk.naturerhverv.fishery.base.area.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LISTCommonGetLists {

    @WebMethod(operationName = "GetLists", action = "GetLists")
    @WebResult(name = "ListsResponse", targetNamespace = "urn:dk:naturerhverv:fishery:service:lists:v1", partName = "part")
    public ListsResponse getLists(
        @WebParam(partName = "part", name = "ListsRequest", targetNamespace = "urn:dk:naturerhverv:fishery:service:lists:v1")
        ListsRequest part
    );
}
