package dk.naturerhverv.fishery.sm.cmon.common.findsimplecustomerinfos.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-10-27T13:08:19.821+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindSimpleCustomerInfos:v1.0", name = "CMON.Customer.FindCustomerInfos")
@XmlSeeAlso({dk.naturerhverv.fishery.dm.vess.v1.ObjectFactory.class, dk.naturerhverv.fishery.dm.cmon.v1.ObjectFactory.class, dk.naturerhverv.fishery.sm.cmon.common.findsimplecustomerinfos.v1.ObjectFactory.class, dk.naturerhverv.fishery.dm.base.v1.ObjectFactory.class, dk.naturerhverv.fishery.dm.geod.v1.ObjectFactory.class, dk.naturerhverv.fishery.dm.indv.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CMONCustomerFindCustomerInfos {

    @WebMethod(operationName = "FindCustomerInfos", action = "FindCustomerInfos")
    @WebResult(name = "FindCustomerInfosResponse", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindSimpleCustomerInfos:v1.0", partName = "part")
    public dk.naturerhverv.fishery.sm.cmon.common.findsimplecustomerinfos.v1.FindCustomerInfosResponseType findCustomerInfos(
        @WebParam(partName = "part", name = "FindCustomerInfosRequest", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindSimpleCustomerInfos:v1.0")
        dk.naturerhverv.fishery.sm.cmon.common.findsimplecustomerinfos.v1.FindCustomerInfosRequestType part
    );
}
