package dk.naturerhverv.fishery.sm.cmon.common.findcustomer.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-10-27T13:08:19.413+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindCustomer:v1.0", name = "CMON.Customer.FindCustomer")
@XmlSeeAlso({dk.fd.dm.geod.v1.ObjectFactory.class, dk.fd.dm.indv.v1.ObjectFactory.class, dk.naturerhverv.fishery.sm.cmon.common.findcustomer.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CMONCustomerFindCustomer {

    @WebMethod(operationName = "FindCustomer", action = "FindCustomer")
    @WebResult(name = "FindCustomerResponse", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindCustomer:v1.0", partName = "part")
    public dk.naturerhverv.fishery.sm.cmon.common.findcustomer.v1.FindCustomerResponse findCustomer(
        @WebParam(partName = "part", name = "FindCustomerRequest", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindCustomer:v1.0")
        dk.naturerhverv.fishery.sm.cmon.common.findcustomer.v1.FindCustomerRequest part
    );
}
