package dk.naturerhverv.fishery.sm.cmon.common.findvessels.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-10-27T13:08:20.703+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindVessels:v1.0", name = "CMON.Vessel.FindVessels")
@XmlSeeAlso({dk.fd.dm.geod.v1.ObjectFactory.class, dk.fd.dm.indv.v1.ObjectFactory.class, dk.naturerhverv.fishery.sm.cmon.common.findvessels.v3.ObjectFactory.class, dk.fd.dm.vess.v1.ObjectFactory.class, dk.fd.dm.cmon.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CMONVesselFindVessels {

    @WebMethod(operationName = "FindVessels", action = "FindVessels")
    @WebResult(name = "FindVesselsResponse", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindVessels:v3.0", partName = "part")
    public dk.naturerhverv.fishery.sm.cmon.common.findvessels.v3.FindVesselsResponseType findVessels(
        @WebParam(partName = "part", name = "FindVesselsRequest", targetNamespace = "urn:dk:naturerhverv:fishery:sm:cmon:Common:FindVessels:v3.0")
        dk.naturerhverv.fishery.sm.cmon.common.findvessels.v3.FindVesselsRequestType part
    );
}
